name: Publish

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun test
      - run: bun pm pack
      - uses: actions/upload-artifact@v4
        with:
          name: package-tarball
          path: boltsocial-*.tgz

  deploy-production:
    name: Deploy / Production
    environment: 'Production'
    needs: 
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          scope: '@boltsocial'
      - uses: actions/setup-node@v4
        with:
          node-version: latest 
          registry-url: 'https://registry.npmjs.org' 
      - run: bun install --frozen-lockfile
      - uses: actions/download-artifact@v4
        with:
          name: package-tarball
      - run: npm publish boltsocial-*.tgz --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
